### ISSUE TITLE
Invalid transfers object

### ISSUE THREAD

**Issue by pezmondo** [bitfinexcom/smidgen#26]
```
$ smidgen multisig transfer 2 ZOTCUFBIQFEFWOSP9DCRLQRNW9MGQWCSP9PGGPEXGYYGRCSHGFQONXQQJEOCCJLGBAJJDFEKGUUKZSCYCHEMPNDOC9 bob multisig.txt --provider=http://127.0.0.1:14999
Enter your seed: 
ERR! Invalid transfers object 
ERR! Error: Invalid transfers object
ERR!     at Object.invalidTransfers (/usr/local/lib/node_modules/smidgen/node_modules/iota.lib.js/lib/errors/inputErrors.js:23:16)
ERR!     at Multisig.initiateTransfer (/usr/local/lib/node_modules/smidgen/node_modules/iota.lib.js/lib/multisig/multisig.js:109:32)
ERR!     at continueWithSeed (/usr/local/lib/node_modules/smidgen/lib/cmds/multisig.js:218:21)
ERR!     at getSeed (/usr/local/lib/node_modules/smidgen/lib/cmds/multisig.js:182:5)
ERR!     at read (/usr/local/lib/node_modules/smidgen/lib/get-seed.js:16:5)
ERR!     at Interface.onLine (/usr/local/lib/node_modules/smidgen/node_modules/read/lib/read.js:111:5)
ERR!     at emitOne (events.js:115:13)
ERR!     at Interface.emit (events.js:210:7)
ERR!     at Interface._onLine (readline.js:282:10)
ERR!     at Interface._line (readline.js:631:8)
ERR! 
ERR! 
ERR! smidgen: 1.1.0 node: v8.6.0
ERR! please open an issue including this log on https://github.com/bitfinexcom/smidgen/issues
```
using iotaproxy to forward PoW

**Comment by robertkowalski** [comment]
this could be related to the latest changes in the network. double checking now.

**Comment by robertkowalski** [comment]
found the issue. will publish an update soon!

**Comment by pezmondo** [comment]
great. I could not grab the latest update from npm though
