### ISSUE TITLE
Request Error: inconsistent tips pair selected

### ISSUE THREAD

**Issue by loebelch** [bitfinexcom/smidgen#38]
When trying "smidgen generate-address" I get an error "Request Error: inconsistent tips pair selected"

```
# smidgen generate-address
Enter your seed: *********************
info Generating address...
ERR! Request Error: inconsistent tips pair selected
ERR! Error: Request Error: inconsistent tips pair selected
ERR!     at Object.requestError (/www/development/iota/smidgen/node_modules/iota.lib.js/lib/errors/requestErrors.js:11:12)
ERR!     at makeRequest.prepareResult (/www/development/iota/smidgen/node_modules/iota.lib.js/lib/utils/makeRequest.js:293:24)
ERR!     at exports.XMLHttpRequest.request.onreadystatechange (/www/development/iota/smidgen/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
ERR!     at exports.XMLHttpRequest.dispatchEvent (/www/development/iota/smidgen/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
ERR!     at setState (/www/development/iota/smidgen/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
ERR!     at IncomingMessage.<anonymous> (/www/development/iota/smidgen/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
ERR!     at emitNone (events.js:111:20)
ERR!     at IncomingMessage.emit (events.js:208:7)
ERR!     at endReadableNT (_stream_readable.js:1055:12)
ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
ERR!
ERR!
ERR! smidgen: 1.2.1 - iota.lib.js: 0.4.7 - node: v8.9.4
ERR! please open an issue including this log on https://github.com/bitfinexcom/smidgen/issues
```

**Comment by loebelch** [comment]
It seems that this issue is only occuring when using default provider (http://iota.bitfinex.com:80).
I have changed to a different full node - after that the generation was successfull.
